branch-defaults:
  master:
    environment: thirtyOneWordpress-dev
environment-defaults:
  thirtyOneWordpress-dev:
    branch: null
    repository: null
global:
  application_name: thirty one-wordpress
  default_ec2_keyname: thirtyone-server
  default_platform: PHP 7.1 running on 64bit Amazon Linux
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: thirtyone-eb-desktop-deploy
  sc: git
  workspace_type: Application
